# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb28bf9ecf975c753e35c62502b52aaf156aee7e66ff805b57ac673e12c41d13e9e30030ec1b291f6f10f31a8f733a7e64b184b529b65cb8efd16ffc4a01519

test:
  secret_key_base: 3ac6a56c44771b516075590f9974ef28d1e2c9a3050e652cb331fcf6464717dcd08da7faed7a617a5f42ee51da6e03beb7ced761e0a6e456e9bccb56073f562a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
